#!/usr/bin/with-contenv bash

[[ ! -d /config ]] && \
    mkdir /config

[[ ! -f /config/config.yaml ]] && \
    cp /app/config.yaml.example /config/config.yaml

[[ ! -L /app/config.yaml ]] && \
    ln -s /config/config.yaml /app/config.yaml

[[ -z "$API_KEY" ]] && \
  echo "Please pass your API_KEY as an environment variable in your docker run command. See docker info for more details." && \
  API_KEY = "abcdef123456"

sed 's/^API_KEY: .*$/API_KEY: $API_KEY"/g' -i /config/config.yaml

echo "To access the api use the following api key: $API_KEY"
