#!/usr/bin/with-contenv bash

[[ ! -d /config ]] && \
    mkdir /config

[[ ! -f /config/config.yaml ]] && \
    cp /app/config.yaml.example /config/config.yaml

[[ ! -L /app/config.yaml ]] && \
    ln -s /config/config.yaml /app/config.yaml
